apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
data:
  username: YWRtaW4= # base64 encoded "admin"
  password: MTIzNDU2 # base64 encoded "123456"
  token: YUtsM2hKa0UzNA== # base64 encoded "aKl3hJkE34"