apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: nextcloud
type: Opaque
data:
  postgresql-username: bmV4dGNsb3Vk
  postgresql-password: Y2hhbmdlbWU=
  postgresql-root-password: Y2hhbmdlbWU=
  database: bmV4dGNsb3Vk
