# Private network
networks:
  nextcloud:

# Persistent volumes
volumes:
  caddy:
  db:
  nextcloud:

# Containers
services:

  # MariaDB database
  db:
    image: mariadb:11.2.4
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MARIADB_AUTO_UPGRADE
      - MARIADB_DISABLE_UPGRADE_BACKUP

  # Redis cache
  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    restart: always
    networks:
      - nextcloud

  # Nextcloud app
  app:
    image: nextcloud:29.0.3-fpm
    container_name: app
    restart: always
    networks:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
      - REDIS_HOST
      - OVERWRITEPROTOCOL
      - OVERWRITEHOST
      - TRUSTED_PROXIES
      - APACHE_DISABLE_REWRITE_IP
    depends_on:
      - caddy
      - db
      - redis

  # Nginx web server
  web:
    image: nginx:1.27.0-alpine
    container_name: web
    restart: always
    networks:
      - nextcloud
    # ports:
    #   - 127.0.0.1:8080:80
    links:
      - app
    labels:
      - "caddy.reverse_proxy=true"
      - "caddy.header.Strict-Transport-Security=max-age=15552000;"
      - "caddy.rewrite_0=/.well-known/carddav /remote.php/dav"
      - "caddy.rewrite_1=/.well-known/caldav /remote.php/dav"
      - "caddy.rewrite_2=/.well-known/webfinger /index.php/.well-known/webfinger"
      - "caddy.rewrite_3=/.well-known/nodeinfo /index.php/.well-known/nodeinfo"
    volumes:
      - nextcloud:/var/www/html:z,ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro

  # Cron job
  cron:
    image: nextcloud:29.0.3-fpm
    container_name: cron
    restart: always
    networks:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  # Caddy reverse proxy
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    restart: always
    networks:
      - nextcloud
    ports:
      - 8080:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./web/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data