apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    # path: /data/nextcloud-pv/
    path: /tmp/hostpath-provisioner/nextcloud/nextcloud-pv/

