apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    # path: /data/postgresql-pv/
    path: /tmp/hostpath-provisioner/nextcloud/postgresql-pv/

