# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
  { :hostname => "k01", :ip => "192.168.133.80" },
  # { :hostname => "k02", :ip => "192.168.133.81" },
  # { :hostname => "k03", :ip => "192.168.133.83" },
]

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/39-cloud-base"

  config.vm.provider :libvirt do |lv|
    lv.qemu_use_session = false
    lv.memory = 2048
    lv.cpus = 2
  end

  servers.each do |conf|
    config.vm.define conf[:hostname] do |node|
      node.vm.hostname = conf[:hostname]
      node.vm.synced_folder ".", "/vagrant", disabled: true

      # Network
      node.vm.network :private_network,
                      :libvirt__network_name => 'kub-devel'

      # Provisioning
      node.vm.provision :shell, 
                        :path => './scripts/0_provisioning.sh',
                        :args => [ conf[:ip] ]

      # Kubernetes installation
      node.vm.provision :shell,
                        :path => './scripts/1_kubernetes.sh',
                        :privileged => true

      # k9s and Helm installation
      node.vm.provision :shell,
                        :path => './scripts/2_utilities.sh'

      # Removing Taints (for single node cluster)
      node.vm.provision :shell,
                        :path => './scripts/3_taint.sh',
                        :privileged => false

      # YAML files for Nextcloud
      node.vm.provision :file,
                        source: "./nextcloud",
                        destination: "/home/vagrant/"

      # Nextcloud set-up and installation
      node.vm.provision :shell,
                        :path => './scripts/4_nextcloud.sh',
                        :privileged => false

      # Port forwarding from vm to host
      node.vm.network "forwarded_port", guest: 8080, host: 8080

    end
  end
end
